---
- src: https://github.com/ansible-community/ansible-vault.git
  name: ansible-community.ansible-vault
  scm: git
  version: master

- name: weareinteractive.users
- name: geerlingguy.pip
- name: geerlingguy.ntp
- name: geerlingguy.security
- name: viasite-ansible.zsh
- name: ansible-elasticsearch
- name: ansible-traefik
- name: ansible-kasm_server
- name: ansible-vault

